### ISSUE TITLE
ODM2 to WaterML 1.1 Controlled Vocabularies Mapping.

### ISSUE THREAD

**Issue by lsetiawan** [ODM2/WOFpy#160]
#152 is getting long. Opening this issue for the mapping of CV. Following up from https://github.com/ODM2/WOFpy/issues/160#issuecomment-317583449. Please edit as you see fit.

The format is waterml cv as key then list of ODM2 cv that matches as values. **I am only mapping the ODM2 CV terms that don't match with WaterML 1.1 terms.**

---
<details>
<summary>Censorcode</summary>

## Censorcode [(WaterML 1.1 CV)](http://his.cuahsi.org/mastercvreg/edit_cv11.aspx?tbl=CensorCodeCV&id=773577794)

```yaml
censorcode:
  gt:
  - Greater than
  lt:
  - Less than
  nc:
  - Not censored
  nd:
  - Non-detect
  pnq:
  - Present but not quantified
```
</details>
<details>
<summary>Datatype</summary>

## Datatype [(WaterML 1.1 CV)](http://his.cuahsi.org/mastercvreg/edit_cv11.aspx?tbl=DataTypeCV&id=789577851)

```yaml
datatype:
  Best Easy Systematic Estimator:
  - Best easy systematic estimator
  Constant Over Interval:
  - Constant over interval
  StandardDeviation:
  - Standard deviation
```
</details>

<details>
<summary>Samplemedium</summary>

## Samplemedium [(WaterML 1.1 CV)](http://his.cuahsi.org/mastercvreg/edit_cv11.aspx?tbl=SampleMediumCV&id=821577965)

```yaml
samplemedium:
  Not Relevant:
  - Not applicable
  Other:
  - Rock
  - Regolith
  - Mineral
  - Ice
  - Habitat
  Surface water:
  - Liquid aqueous
  - Liquid organic
  Suspended particulate matter:
  - Particulate
  Tissue:
  - Organism
  Tree:
  - Vegetation
  Wellhead Gas:
  - Gas
```
</details>

<details>
<summary>Unitstype</summary>

## Unitstype [(WaterML 1.1 CV)](http://his.cuahsi.org/mastercvreg/edit_cv11.aspx?tbl=Units&id=1125579048)

</details>

<details>
<summary>Generalcategory</summary>

## Generalcategory [(WaterML 1.1 CV)](http://his.cuahsi.org/mastercvreg/edit_cv11.aspx?tbl=GeneralCategoryCV&id=805577908)

</details>

<details>
<summary>Valuetype</summary>

## Valuetype [(WaterML 1.1 CV)](http://his.cuahsi.org/mastercvreg/edit_cv11.aspx?tbl=ValueTypeCV&id=1141579105)

</details>

---
